finalarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

#Trajectory Controllers----------------------------------------
  finalarm_joint_trajectory_action_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

# Position Controllers ----------------------------------------
  joint_8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_8
    pid: {p: 500, i: 0.01, d: 0.0}

  joint_9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_9
    pid: {p: 500, i: 0.01, d: 0.0}

