finalarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Position Controllers ----------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10000, i: 0.01, d: 0.0}

  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10000, i: 0.01, d: 0.0}

  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_7
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_8
    pid: {p: 1000, i: 0.01, d: 0.0}

  joint_9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_9
    pid: {p: 1000, i: 0.01, d: 0.0}

